
.TH bm 1 "21 May 2018" "v1.1.21"
.SH NAME
.B bm 
\- Browser-Mirror CLI tool
.SH DESCRIPTION
.B bm 
is the command-line tool for managing the Browser-Mirror websocket server, it's logs, and installing the bm-client.js client-side counterpart that communicates with the server.
.SH SYNOPSIS
.B Start the server:
.PP
    bm server start [port number]
.PP Port number default to 1337 if omitted.
.PP
.B Stop the server:
.PP
    bm server stop
.PP
.B Install the client-side JS file:
.PP
    bm client install /path/to/install/to
.PP
.B Update bm:
.PP
    bm update
.PP
.B get server status:
.PP
    bm server status
.PP
.B Uninstall bm:
.PP
    bm uninstall
.PP
.B Get bm version:
.PP
    bm --version
.PP
.B View help test:
.PP
    bm --help