
.TH bm 1 "18 May 2018" "v1.1.4"
.SH NAME
.B bm 
\- Browser-Mirror CLI tool
.SH DESCRIPTION
.B bm 
is the command-line tool for managing the Browser-Mirror websocket server, it's logs, and installing the bm-client.js client-side counterpart that communicates with the server.
.SH SYNOPSIS
.B Start the server:
.PP
    bm server start
.PP
.B Stop the server:
.PP
    bm server stop
.PP
.B Install the client-side JS file:
.PP
    bm client install 
.I/path/to/install/to
.PP
.B Get bm version:
.PP
    bm --version
.PP
.B Update bm:
.PP
    bm update
PP
.B Uninstall bm:
.PP
    bm uninstall
.PP
.B View help test:
.PP
    bm --help