
.TH bm 1 "17 May 2018" "version 1.1.0"
.SH NAME
.B bm 
\- Browser-Mirror CLI tool
.SH DESCRIPTION
.B bm 
is the command-line tool for managing the Browser-Mirror websocket server, it's logs, and installing the bm-client.js client-side counterpart that communicates with the server.
.SH SYNOPSIS
.B Start the server:
.PP
    bm server start
.PP
.B Stop the server:
.PP
    bm server stop
.PP
.B Install the client-side JS file:
.PP
    bm client install 
.I/path/to/install/to
.PP
.B Get bm version:
.PP
    bm --version
.PP
.B View help test:
.PP
    bm --help