#!/usr/bin/env bash

HERE=$(pwd)
npm init -y
npm install browser-mirror
mv ./node_modules/browser-mirror/bm-server ./bm-server
chmod +x bm-server

#if [ -f /etc/bashrc ]; then
#	printf '%s\n%s\n' '' "$(cat /etc/bashrc)" >/etc/bashrc
#	printf '%s%s%s\n%s\n' 'export PATH="$PATH:' $HERE '"' "$(cat /etc/bashrc)" >/etc/bashrc
#	printf '%s\n%s\n' '# Add bm-server to $PATH' "$(cat /etc/bashrc)" >/etc/bashrc
#	printf '%s\n%s\n' '' "$(cat /etc/bashrc)" >/etc/bashrc
#   source /etc/bashrc
#fi

if [ -f /etc/profile ]; then
	printf '%s\n%s\n' '' "$(cat /etc/profile)" >/etc/profile
	printf '%s%s%s\n%s\n' 'export PATH="$PATH:' $HERE '"' "$(cat /etc/profile)" >/etc/profile
	printf '%s\n%s\n' '# Add bm-server to $PATH' "$(cat /etc/profile)" >/etc/profile
	printf '%s\n%s\n' '' "$(cat /etc/profile)" >/etc/profile
    source /etc/profile
fi

touch logs.txt && chmod 777 logs.txt

# sudo -s
# source /dev/stdin <<< "$(curl https://raw.githubusercontent.com/Pamblam/browser-mirror/dynamically-created-elements/installer)"
